// AUTO-GENERATED by update-lab.py — do not edit manually
// Last updated by R2D2/3PO after latest work session

export interface Agent {
  id: string
  name: string
  emoji: string
  role: string
  status: 'online' | 'scheduled' | 'ondemand' | 'learning'
  statusLabel: string
  description: string
  tags: string[]
}

export interface Project {
  name: string
  status: 'live' | 'active' | 'planned'
  stack: string[]
  description: string
  url?: string
}

export interface FocusItem {
  emoji: string
  text: string
}

export const agents: Agent[] = [
  { id: 'r2d2', name: 'R2D2', emoji: '🤖', role: 'Orchestrator & Chief of Staff', status: 'online' as const, statusLabel: 'Always Online', description: 'The brain of the operation. Coordinates all agents, handles communications across WhatsApp, manages memory, and dispatches work to the team. Built on Claude Sonnet.', tags: ['Orchestration', 'Memory', 'WhatsApp', 'Claude'] },
  { id: 'guardian', name: 'Guardian', emoji: '🛡️', role: 'Infrastructure Watchdog', status: 'online' as const, statusLabel: 'Running 24/7', description: 'Silent sentinel monitoring all services — OpenClaw, containers, Nginx. Self-heals before anyone notices. Only alerts when human action is needed.', tags: ['Docker', 'Self-healing', 'Monitoring', 'Infra'] },
  { id: 'maxwell', name: 'Maxwell', emoji: '📰', role: 'Senior News Editor', status: 'scheduled' as const, statusLabel: 'Daily at 5AM EST', description: 'Autonomous news editor that curates The Headlines Today every morning. Pulls global news, writes summaries, generates PDF + audio briefing covering all headlines across all sections.', tags: ['News', 'PDF', 'Audio', 'Daily'] },
  { id: '3po', name: '3PO', emoji: '🧑‍💻', role: 'Senior Coding Partner & Swarm Lead', status: 'ondemand' as const, statusLabel: 'On Demand', description: 'Claude Code instance spawned for any engineering task. Works solo or deploys as a parallel swarm — multiple instances tackling independent workstreams simultaneously. Builds features, fixes bugs, writes architecture.', tags: ['Claude Code', 'Full-Stack', 'Swarm', 'Architecture'] },
  { id: 'yoda', name: 'Yoda', emoji: '🧙', role: 'Self-Evolving Research Agent', status: 'learning' as const, statusLabel: 'Learning', description: 'Feeds on research papers and builds its own VL-JEPA model. Extracts knowledge, updates understanding, improves code autonomously. Currently at v0.5 — 161M parameters.', tags: ['VL-JEPA', 'Self-Evolving', 'PyTorch', 'Research'] },
  { id: 'aria', name: 'ARIA', emoji: '🎯', role: 'AI HR & Career Intelligence', status: 'ondemand' as const, statusLabel: 'On Demand', description: 'Tailors resumes for ATS + human readers, optimizes LinkedIn, generates portfolio sites, career strategy. Every candidate is a brand. Top 1% globally.', tags: ['Career', 'Resume', 'LinkedIn', 'Branding'] },
]

export const projects: Project[] = [
  { name: 'The Headlines Today', status: 'live' as const, stack: ['React', 'TypeScript', 'Vite', 'Claude AI', 'Docker', 'Nginx'], description: 'AI-curated daily newspaper. Maxwell fetches global RSS feeds, writes publication-ready summaries, generates PDF + audio briefing covering all headlines — published every morning at 5 AM EST.', url: 'https://news.suhailtaj.cloud', },
  { name: 'Prompt Studio', status: 'live' as const, stack: ['React', 'Node.js', 'Docker', 'Nginx'], description: 'A personal prompt engineering workspace. Design, test, and iterate on prompts for LLMs with a clean, focused interface.', url: 'https://lab.suhailtaj.cloud/prompt-studio/', },
  { name: 'Yoda — VL-JEPA Learning System', status: 'active' as const, stack: ['Python', 'PyTorch', 'Claude', 'BERT', 'ViT', 'Docker'], description: 'Self-evolving agent that learns Vision-Language JEPA from research papers and autonomously builds its own product embedding model. v0.5 — 161M parameters, trained on Amazon Berkeley Objects dataset.',  },
]

export const focusItems: FocusItem[] = [
  { emoji: '📰', text: 'The Headlines Today — AI newspaper publishing daily at 5AM EST via Maxwell' },
  { emoji: '🧪', text: 'Prompt Studio — Live prompt engineering workspace at lab.suhailtaj.cloud' },
  { emoji: '🧙', text: 'Yoda — Self-evolving VL-JEPA agent, v0.5 with 161M parameters' },
  { emoji: '🧠', text: 'VL-JEPA — Training a vision-language model from research papers' },
]

export const labStats = {
  agents: 6,
  liveProjects: 2,
  modelTraining: 1,
}

export const statusColors: Record<string, string> = {
  online: '#22c55e',
  scheduled: '#f59e0b',
  ondemand: '#3b82f6',
  learning: '#a855f7',
}
